name: ci
on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    build-and-test:
        name: build and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: yarn
            - run: yarn
            - run: yarn build
            - run: yarn test
    test-e2e:
        name: test e2e
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: yarn
            - run: yarn build
            - uses: cypress-io/github-action@v4
              with:
                  install: false
                  working-directory: apps/web
                  start: yarn start
