name: ci
on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    build-and-test:
        name: build and test
        runs-on: ubuntu-latest
        environment: testing
        env:
            PORT: ${{vars.PORT}}
            NEXT_PUBLIC_GAME_SERVER_URL: ${{vars.NEXT_PUBLIC_GAME_SERVER_URL}}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: yarn
            - run: yarn
            - run: yarn build
            - run: yarn test

    test-e2e:
        name: test e2e
        runs-on: ubuntu-latest
        environment: testing
        # TODO: there is some wonkyness going on with setting `PORT` env that
        # backend uses but is forwarded to cypress runner and causes it to run
        # on the wrong port -
        # https://github.com/auto200/tiki-toki/actions/runs/5638695094/job/15273272357
        # we do not need backend to run cypress tests yet, so it's fine for now
        env:
            NEXT_PUBLIC_GAME_SERVER_URL: ${{vars.NEXT_PUBLIC_GAME_SERVER_URL}}
        steps:
            - uses: actions/checkout@v3
            - run: yarn
            - run: yarn build
            - uses: cypress-io/github-action@v4
              with:
                  install: false
                  working-directory: apps/web
                  start: yarn start
